version: "3.9"
services:
  db:
    image: mysql:8.0.21
    container_name: database
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=9193999
    restart: "always"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE

  frontend:
    build: ./client
    container_name: frontend_app
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 3000:3000
    restart: always
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3000" ] 
      timeout: 10s
      retries: 5
  backend:
    build: ./server
    container_name: backend_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PWD=9193999
      - DB_HOST=db
      - DB_NAME=crud_app
      - DB_PORT=3306
      - DB_DIALECT=mysql
    restart: always
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
